#==============
def generate_javascript(crc16_text: str) -> str:
	"""Bind native drag events to one item's existing interaction callbacks."""
	js = '<script>\n(function() {\n'
	js += f"  const container = document.getElementById('question_html_{crc16_text}');\n"
	js += "  container.qtiBindDrag = ({sources, targets, reorder, drop}) => {\n"
	js += "    let active = null;\n"
	js += "    function clearTargets() {\n"
	js += "      container.querySelectorAll(targets).forEach(target => {\n"
	js += "        target.classList.remove('qti-drop-target', 'qti-drop-before', 'qti-drop-after');\n"
	js += "      });\n"
	js += "    }\n"
	js += "    function cancel() {\n"
	js += "      if (active) active.classList.remove('qti-dragging');\n"
	js += "      active = null;\n"
	js += "      clearTargets();\n"
	js += "    }\n"
	js += "    function after(event, target) {\n"
	js += "      const bounds = target.getBoundingClientRect();\n"
	js += "      return event.clientY > bounds.top + bounds.height / 2;\n"
	js += "    }\n"
	js += "    container.addEventListener('dragstart', event => {\n"
	js += "      const source = event.target.closest(sources);\n"
	js += "      if (!source || source.disabled || source.getAttribute('draggable') !== 'true') {\n"
	js += "        event.preventDefault();\n"
	js += "        return;\n"
	js += "      }\n"
	js += "      active = source;\n"
	js += "      event.dataTransfer.setData('text/plain', source.dataset.value);\n"
	js += "      event.dataTransfer.effectAllowed = 'move';\n"
	js += "      source.classList.add('qti-dragging');\n"
	js += "    });\n"
	js += "    container.addEventListener('dragover', event => {\n"
	js += "      const target = event.target.closest(targets);\n"
	js += "      if (!active || !target || target === active) return;\n"
	js += "      event.preventDefault();\n"
	js += "      event.dataTransfer.dropEffect = 'move';\n"
	js += "      clearTargets();\n"
	js += "      target.classList.add('qti-drop-target');\n"
	js += "      if (reorder) target.classList.add(after(event, target) ? 'qti-drop-after' : 'qti-drop-before');\n"
	js += "    });\n"
	js += "    container.addEventListener('dragleave', event => {\n"
	js += "      const target = event.target.closest(targets);\n"
	js += "      if (target && !target.contains(event.relatedTarget)) {\n"
	js += "        target.classList.remove('qti-drop-target', 'qti-drop-before', 'qti-drop-after');\n"
	js += "      }\n"
	js += "    });\n"
	js += "    container.addEventListener('drop', event => {\n"
	js += "      const target = event.target.closest(targets);\n"
	js += "      if (!target) return;\n"
	js += "      event.preventDefault();\n"
	# ASVS 2.2.1: accept only an active source from this item, never external payload markup.
	js += "      const source = active;\n"
	js += "      const valid = source && !source.disabled && target !== source &&\n"
	js += "        event.dataTransfer.getData('text/plain') === source.dataset.value;\n"
	js += "      cancel();\n"
	js += "      if (valid) drop(source, target, after(event, target));\n"
	js += "    });\n"
	js += "    container.addEventListener('dragend', cancel);\n"
	js += "    container.qtiCancelDrag = cancel;\n"
	js += "  };\n})();\n</script>\n"
	return js
