#==============
def generate_javascript(crc16_text: str) -> str:
	"""Share assignment state between native dragging, click, tap, and keyboard."""
	js = '<script>\n(function() {\n'
	js += f"  const container = document.getElementById('question_html_{crc16_text}');\n"
	js += "  const choices = Array.from(container.querySelectorAll('.qti-match-choice'));\n"
	js += "  const slots = Array.from(container.querySelectorAll('.qti-match-slot'));\n"
	js += "  const status = container.querySelector('[role=status]');\n"
	js += "  let selected = null;\n"
	js += "  function select(choice) {\n"
	js += "    selected = choice;\n"
	js += "    choices.forEach(button => {\n"
	js += "      button.setAttribute('aria-pressed', button === selected ? 'true' : 'false');\n"
	js += "      button.classList.toggle('qti-selected', button === selected);\n"
	js += "    });\n"
	js += "  }\n"
	js += "  function emptySlot(slot) {\n"
	js += "    delete slot.dataset.value;\n"
	js += "    slot.className = 'qti-match-slot';\n"
	js += "    slot.textContent = 'Drop Your Choice Here';\n"
	js += "    slot.removeAttribute('title');\n"
	js += "    slot.setAttribute('aria-label', 'Assign a choice to prompt ' + slot.dataset.prompt);\n"
	js += "  }\n"
	js += "  function assign(choice, slot, move = false) {\n"
	js += "    const previous = slot.dataset.value;\n"
	js += "    const cleared = move ? slots.filter(other => other !== slot &&\n"
	js += "      other.dataset.value === choice.dataset.value) : [];\n"
	js += "    cleared.forEach(emptySlot);\n"
	# ASVS 1.2.1: use plain text; CSS clips to the actual slot width without losing content.
	js += "    const text = choice.innerText.trim().replace(/\\s+/g, ' ');\n"
	js += "    slot.textContent = text;\n"
	js += "    slot.title = text;\n"
	js += "    slot.dataset.value = choice.dataset.value;\n"
	js += "    slot.className = 'qti-match-slot ' + Array.from(choice.classList).find(name => name.startsWith('qti-choice-'));\n"
	js += "    slot.setAttribute('aria-label', 'Prompt ' + slot.dataset.prompt + ': ' + text + '. Replace with selected choice');\n"
	js += "    select(null);\n"
	js += f"    clearFeedback_{crc16_text}();\n"
	js += "    slot.focus();\n"
	# ASVS 1.2.1: announcements are plain text, not interpreted HTML.
	js += "    let message = cleared.length ? choice.dataset.letter + ' moved from prompt ' +\n"
	js += "      cleared.map(other => other.dataset.prompt).join(', ') + ' to prompt ' + slot.dataset.prompt + '.' :\n"
	js += "      'Assigned ' + text + ' to prompt ' + slot.dataset.prompt + '.';\n"
	js += "    if (previous && previous !== choice.dataset.value) {\n"
	js += "      message += ' Replaced ' + choices.find(button => button.dataset.value === previous).dataset.letter + '.';\n"
	js += "    }\n"
	js += "    status.textContent = message;\n"
	js += "  }\n"
	js += "  container.qtiBindDrag({\n"
	js += "    sources: '.qti-match-choice', targets: '.qti-match-slot', reorder: false,\n"
	# The drag binder's third argument is drop position, not keyboard-move intent.
	js += "    drop: (choice, slot) => assign(choice, slot)\n"
	js += "  });\n"
	js += "  container.addEventListener('click', event => {\n"
	js += "    const choice = event.target.closest('.qti-match-choice');\n"
	js += "    if (choice) {\n"
	js += "      select(choice === selected ? null : choice);\n"
	# Safari does not focus buttons on tap; keep Escape and keyboard continuation local.
	js += "      choice.focus();\n"
	js += "      status.textContent = selected ? 'Selected ' + selected.querySelector('.qti-choice-content').textContent.trim() + '. Choose a prompt.' : 'Selection cleared.';\n"
	js += "      return;\n"
	js += "    }\n"
	js += "    const slot = event.target.closest('.qti-match-slot');\n"
	js += "    if (!slot) return;\n"
	js += "    if (!selected) { status.textContent = 'Select a choice first.'; return; }\n"
	js += "    assign(selected, slot);\n"
	js += "  });\n"
	js += "  container.addEventListener('keydown', event => {\n"
	js += "    if (event.key === 'Escape') {\n"
	js += "      select(null); status.textContent = 'Selection cleared.'; return;\n"
	js += "    }\n"
	js += "    const slot = event.target.closest('.qti-match-slot');\n"
	js += "    if (!slot || event.ctrlKey || event.metaKey || event.altKey || event.isComposing) return;\n"
	# ASVS 2.2.1: resolve only a displayed letter belonging to this question.
	js += "    const choice = choices.find(button => button.dataset.letter === event.key.toUpperCase());\n"
	js += "    if (!choice) return;\n"
	js += "    event.preventDefault();\n"
	js += "    assign(choice, slot, true);\n"
	js += "  });\n"
	js += "  container.qtiResetGame = () => {\n"
	js += "    container.qtiCancelDrag();\n"
	js += "    slots.forEach(emptySlot);\n"
	js += "    select(null);\n"
	js += "    status.textContent = 'Matches reset.';\n"
	js += "  };\n"
	js += "})();\n</script>\n"
	return js
