#==============
def generate_javascript(crc16_text: str) -> str:
	"""Move existing rows so their content survives reordering and reset."""
	js = '<script>\n(function() {\n'
	js += f"  const container = document.getElementById('question_html_{crc16_text}');\n"
	js += "  const list = container.querySelector('.qti-order-list');\n"
	js += "  const initialRows = Array.from(list.children);\n"
	js += "  const status = container.querySelector('[role=status]');\n"
	js += "  function updatePositions() {\n"
	js += "    Array.from(list.children).forEach((row, index) => {\n"
	js += "      row.querySelector('.qti-order-position').textContent = index + 1;\n"
	js += "      row.querySelectorAll('.qti-order-move').forEach(button => {\n"
	js += "        const up = button.dataset.direction === 'up';\n"
	js += "        button.disabled = up ? index === 0 : index === list.children.length - 1;\n"
	js += "        button.setAttribute('aria-label', `Move item ${index + 1} ${up ? 'earlier' : 'later'}`);\n"
	js += "      });\n"
	js += "    });\n"
	js += "  }\n"
	js += "  function place(row, before, button) {\n"
	js += "    list.insertBefore(row, before);\n"
	js += "    updatePositions();\n"
	# Native disabled buttons cannot retain focus at an endpoint.
	js += "    const focusButton = button.disabled ? row.querySelector('.qti-order-move:not(:disabled)') : button;\n"
	js += "    focusButton.focus();\n"
	js += f"    clearFeedback_{crc16_text}();\n"
	js += "    status.textContent = row.querySelector('.qti-choice-content').textContent.trim() +\n"
	js += "      ' moved to position ' + row.querySelector('.qti-order-position').textContent + '.';\n"
	js += "  }\n"
	js += "  function move(button, direction) {\n"
	js += "    const row = button.closest('.qti-order-row');\n"
	js += "    const neighbor = direction === 'up' ? row.previousElementSibling : row.nextElementSibling;\n"
	js += "    if (neighbor) place(row, direction === 'up' ? neighbor : neighbor.nextElementSibling, button);\n"
	js += "  }\n"
	js += "  container.qtiBindDrag({\n"
	js += "    sources: '.qti-order-row', targets: '.qti-order-row', reorder: true,\n"
	js += "    drop(row, target, after) {\n"
	js += "      place(row, after ? target.nextElementSibling : target, row.querySelector('.qti-order-move:not(:disabled)'));\n"
	js += "    }\n"
	js += "  });\n"
	js += "  list.addEventListener('click', event => {\n"
	js += "    const button = event.target.closest('.qti-order-move');\n"
	js += "    if (button) move(button, button.dataset.direction);\n"
	js += "  });\n"
	js += "  list.addEventListener('keydown', event => {\n"
	js += "    const button = event.target.closest('.qti-order-move');\n"
	js += "    if (!button || !['ArrowUp', 'ArrowDown'].includes(event.key)) return;\n"
	js += "    event.preventDefault();\n"
	js += "    move(button, event.key === 'ArrowUp' ? 'up' : 'down');\n"
	js += "  });\n"
	js += "  container.qtiResetGame = () => {\n"
	js += "    container.qtiCancelDrag();\n"
	js += "    initialRows.forEach(row => list.appendChild(row));\n"
	js += "    updatePositions();\n"
	js += "    status.textContent = 'Order reset.';\n"
	js += "  };\n"
	js += "  updatePositions();\n})();\n</script>\n"
	return js
