#!/usr/bin/env python3
"""
Build control ZIPs from the real Blackboard exports under SAMPLES/.

SAMPLES/blackboard_learn_classic-bb_export/, SAMPLES/blackboard_learn_classic-
qti21_export/, and SAMPLES/blackboard_ultra-qti21_export/ are extracted
directory trees of REAL export packages Blackboard itself produced (not
generated by this repo's writers). Each is read-only evidence for how a real
export ZIP is laid out.

This script re-zips each extracted tree faithfully -- same files, same
relative paths, imsmanifest.xml at the ZIP root with no wrapper directory --
so a human can import the REAL package into the same sandbox used to probe
this repo's generated packages. If the real package also fails to render
images on import, that is an LMS ceiling, not a defect in our writers; if the
real package renders fine, our writers have a findable delta to chase.

Output ZIPs (written to output_probes/controls/ by default):

  control_learn-bbexport.zip
      Re-zip of SAMPLES/blackboard_learn_classic-bb_export/. Import via
      classic Blackboard Learn's "Import Package / View Logs > Import
      Package" path (the same path devel/build_bb_original_probe.py's
      bbexport variant targets).

  control_learn-qti21.zip
      Re-zip of SAMPLES/blackboard_learn_classic-qti21_export/. Import via
      classic Blackboard Learn's "Course Tools > Tests, Surveys and Pools >
      Pools > Import" path (the same path devel/build_bb_original_probe.py's
      qti21 variant targets).

  control_ultra-qti21.zip
      Re-zip of SAMPLES/blackboard_ultra-qti21_export/. Import via
      Blackboard Ultra's question bank / pool import path (the same path
      devel/build_ultra_media_probe.py targets).

This script is read-only with respect to SAMPLES/: it only reads files from
disk and writes new ZIPs elsewhere.
"""

# Standard Library
import os
import argparse
import subprocess

# QTI Package Maker
from qti_package_maker.common import zip_writer

# Map of output ZIP filename -> SAMPLES subdirectory to re-zip. The
# imsmanifest.xml sits directly at the root of each SAMPLES subdirectory
# (verified by inspection), so no wrapper-directory stripping is needed.
CONTROL_ZIP_SOURCES = {
	"control_learn-bbexport.zip": "blackboard_learn_classic-bb_export",
	"control_learn-qti21.zip": "blackboard_learn_classic-qti21_export",
	"control_ultra-qti21.zip": "blackboard_ultra-qti21_export",
}


#============================================
def get_repo_root() -> str:
	"""
	Get the repository root using git rev-parse --show-toplevel.

	Returns:
		str: Absolute path to the repository root.
	"""
	result = subprocess.run(
		["git", "rev-parse", "--show-toplevel"],
		capture_output=True, text=True, check=True,
	)
	repo_root = result.stdout.strip()
	return repo_root


#============================================
def build_control_zip(source_dir: str, zip_path: str) -> str:
	"""
	Re-zip a real SAMPLES export tree into a faithful control ZIP.

	Args:
		source_dir: absolute path to the extracted SAMPLES export tree.
		zip_path: output path for the control ZIP.

	Returns:
		str: the written ZIP path.
	"""
	# collect_directory maps archive path -> absolute source file path for
	# every file under source_dir; build_zip writes them in sorted order so
	# the archive layout stays deterministic.
	archive_map = zip_writer.collect_directory(source_dir)
	written_path = zip_writer.build_zip(zip_path, archive_map)
	return written_path


#============================================
def build_all_control_zips(samples_dir: str, output_dir: str) -> dict:
	"""
	Build all three control ZIPs from SAMPLES/ into output_dir.

	Args:
		samples_dir: absolute path to the repo's SAMPLES/ directory.
		output_dir: directory to write the control ZIPs into.

	Returns:
		dict[str, str]: output ZIP filename -> written ZIP path.
	"""
	os.makedirs(output_dir, exist_ok=True)
	written_paths = {}
	for zip_name, source_subdir in CONTROL_ZIP_SOURCES.items():
		source_dir = os.path.join(samples_dir, source_subdir)
		zip_path = os.path.join(output_dir, zip_name)
		written_paths[zip_name] = build_control_zip(source_dir, zip_path)
	return written_paths


#============================================
def parse_args() -> argparse.Namespace:
	"""
	Parse command-line arguments.

	Returns:
		argparse.Namespace: Parsed arguments.
	"""
	parser = argparse.ArgumentParser(
		description="Re-zip the real SAMPLES/ Blackboard exports into control ZIPs."
	)
	parser.add_argument(
		'-o', '--output', dest='output_dir', default='output_probes/controls',
		help="Directory to write the control ZIPs into.",
	)
	args = parser.parse_args()
	return args


#============================================
def main() -> None:
	args = parse_args()
	repo_root = get_repo_root()
	samples_dir = os.path.join(repo_root, "SAMPLES")
	output_dir = os.path.join(repo_root, args.output_dir)
	written_paths = build_all_control_zips(samples_dir, output_dir)
	for zip_name in sorted(written_paths):
		print(f"Wrote {zip_name}: {written_paths[zip_name]}")


#============================================
if __name__ == '__main__':
	main()
